name = "MRI"
uuid = "66f0c9d0-2f7b-11e9-1fe2-471f5ae892b2"
authors = ["korbi <korbinian90@gmail.com>"]
version = "0.1.0"

[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
GZip = "92fee26a-97fe-5a0c-ad85-20a5f3185b63"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
Mmap = "a63ad114-7e13-5084-954f-fe012c677804"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
