name = "MriResearchTools"
uuid = "557dad86-b9bd-4533-8525-1a39684d020f"
authors = ["Korbinian Eckstein"]
version = "0.1.1"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
NIfTI = "a3a9e032-41b5-5fc4-967a-a6b7a19844d3"
NaNMath = "77ba4419-2d1f-58cd-9bb1-8ffee604a2e3"
ROMEO = "1ea8258b-a15d-4adb-ad20-01632f467a84"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
FFTW = "1"
Interpolations = "0.12"
NIfTI = "0.4"
NaNMath = "0.3.2"
ROMEO = "0.1"
julia = "1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[target]
test = ["Test"]
